const flightData  = [
  {
    "id" : 1,
    "thumbnail": "https://i.pinimg.com/736x/75/b4/69/75b469395dcf237d3a2a5482100e8117--triangle-logo-arrow-logo.jpg",
    "airline": "Delta",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "11:30pm",
    "arrive": "6:57am",
    "duration": "5h 27m",
    "airports": "SFO - JFK",
    "stopsNumber": "Nonstop",
    "stopsAirports": "N/A",
    "price": 77,
    "type": "one-way",
  },
  {
    "id" : 2,
    "thumbnail": "https://i.pinimg.com/736x/75/b4/69/75b469395dcf237d3a2a5482100e8117--triangle-logo-arrow-logo.jpg",
    "airline": "Delta",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "7:05am",
    "arrive": "3:33pm",
    "duration": "5h 28m",
    "airports": "SFO - JFK",
    "stopsNumber": "Nonstop",
    "stopsAirports": "N/A",
    "price": 77,
    "type": "one-way",
  },
  {
    "id" : 3,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/UA.png",
    "airline": "United Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "8:35am",
    "arrive": "5:07pm",
    "duration": "5h 28m",
    "airports": "SFO - JFK",
    "stopsNumber": "Nonstop",
    "stopsAirports": "N/A",
    "price": 77,
    "type": "one-way",
  },
  {
    "id" : 4,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/UA.png",
    "airline": "United Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "1:30pm",
    "arrive": "10:02pm",
    "duration": "5h 32m",
    "airports": "SFO - JFK",
    "stopsNumber": "Nonstop",
    "stopsAirports": "N/A",
    "price": 77,
    "type": "one-way",
  },
  {
    "id" : 5,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/AS.png",
    "airline": "Alaska Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "7:10am",
    "arrive": "3:50pm",
    "duration": "5h 40m",
    "airports": "SFO - JFK",
    "stopsNumber": "Nonstop",
    "stopsAirports": "N/A",
    "price": 77,
    "type": "one-way",
  },
  {
    "id" : 6,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/AS.png",
    "airline": "Alaska Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "10:25am",
    "arrive": "7:05pm",
    "duration": "5h 40m",
    "airports": "SFO - JFK",
    "stopsNumber": "Nonstop",
    "stopsAirports": "N/A",
    "price": 77,
    "type": "one-way",
  },
  {
    "id" : 7,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/AA.png",
    "airline": "American Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "12:06am",
    "arrive": "11:05am",
    "duration": "7h 59m",
    "airports": "SFO - JFK",
    "stopsNumber": 1,
    "stopsAirports": "CLT",
    "price": 119,
    "type": "one-way",
  },
  {
    "id" : 8,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/AA.png",
    "airline": "American Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "8:25am",
    "arrive": "8:06am",
    "duration": "9h 53m",
    "airports": "SFO - JFK",
    "stopsNumber": 1,
    "stopsAirports": "CLT",
    "price": 119,
    "type": "one-way",
  },
  {
    "id" : 9,
    "thumbnail": "https://www.gstatic.com/flights/airline_logos/70px/B6.png",
    "airline": "jetBlue Airlines",
    "date": "11-06-2021",
    "local": "San Francisco",
    "destination": "New York",
    "departure": "9:35pm",
    "arrive": "4:55am",
    "duration": "5h 20m",
    "airports": "SFO - JFK",
    "stopsNumber":"Nonstop" ,
    "stopsAirports": "N/A",
    "price": 119,
    "type": "one-way",
  },

]

export default flightData;