DROP DATABASE IF EXISTS NSDB;

CREATE DATABASE NSDB;
USE NSDB;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    username CHAR(30) NOT NULL,
    password CHAR(50) NOT NULL,
    PRIMARY KEY (id)
);